[build]
  base = "/"   # Go inside the client folder
  command = "npm install && npm run build"   # Ensure dependencies are installed
  publish = "client/build"   # Serve from the build folder

[build.environment]
  NODE_VERSION = "18"  # Use Node.js 18+ (Ensure compatibility)
